projects:
  nueltest3-orderbook-api:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-central-1
        apiId: lp2nc7jbu5bzhi5afc2iwk5fhu
        maxDepth: 2
extensions:
  amplify:
    version: 3
