export const POLKADOT_WALLET_DATA = "POLKADOT_WALLET/DATA";
export const POLKADOT_WALLET_ERROR = "POLKADOT_WALLET/PERROR";
export const POLKADOT_WALLET_FETCH = "POLKADOT_WALLET/FETCH";

export const POLKADOT_WALLET_SET = "POLKADOT_WALLET/SET";
export const POLKADOT_WALLET_RESET = "POLKADOT_WALLET/RESET";
