export const GET_POLKADOT_WALLET_DATA = "POLKADOT_WALLET/GET_POLKADOT_WALLET_DATA";
export const GET_POLKADOT_WALLET_FETCH_ERROR =
  "POLKADOT_WALLET/GET_POLKADOT_WALLET_FETCH_ERROR";
export const GET_POLKADOT_WALLET_FETCH = "POLKADOT_WALLET/GET_POLKADOT_WALLET_FETCH";
export const SET_POLKADOT_WALLET_ACCOUNT = "SET_POLKADOT_WALLET_ACCOUNT";
export const RESET_WALLET_ACCOUNT = "RESET_WALLET_ACCOUNT";
