import { AvatarProps } from "@bigheads/core";

type Props = {
  id: number;
  data: AvatarProps;
};
export const randomAvatars: Props[] = [
  {
    data: {
      skinTone: "yellow",
      eyes: "normal",
      eyebrows: "serious",
      mouth: "openSmile",
      hair: "long",
      facialHair: "none3",
      clothing: "dress",
      accessory: "shades",
      graphic: "react",
      hat: "beanie",
      body: "chest",
      hairColor: "blue",
      clothingColor: "red",
      circleColor: "blue",
      lipColor: "green",
      hatColor: "black",
      faceMaskColor: "blue",
      mask: true,
      faceMask: false,
      lashes: false,
    },
    id: 847206,
  },
  {
    data: {
      skinTone: "red",
      eyes: "wink",
      eyebrows: "leftLowered",
      mouth: "openSmile",
      hair: "afro",
      facialHair: "mediumBeard",
      clothing: "dressShirt",
      accessory: "roundGlasses",
      graphic: "react",
      hat: "turban",
      body: "chest",
      hairColor: "white",
      clothingColor: "red",
      circleColor: "blue",
      lipColor: "turqoise",
      hatColor: "red",
      faceMaskColor: "white",
      mask: true,
      faceMask: false,
      lashes: false,
    },
    id: 895932,
  },
  {
    data: {
      skinTone: "brown",
      eyes: "squint",
      eyebrows: "concerned",
      mouth: "open",
      hair: "balding",
      facialHair: "stubble",
      clothing: "dressShirt",
      accessory: "shades",
      graphic: "gatsby",
      hat: "none4",
      body: "breasts",
      hairColor: "pink",
      clothingColor: "red",
      circleColor: "blue",
      lipColor: "red",
      hatColor: "red",
      faceMaskColor: "blue",
      mask: true,
      faceMask: false,
      lashes: false,
    },
    id: 401174,
  },
  {
    data: {
      skinTone: "red",
      eyes: "heart",
      eyebrows: "leftLowered",
      mouth: "serious",
      hair: "bun",
      facialHair: "stubble",
      clothing: "naked",
      accessory: "tinyGlasses",
      graphic: "none",
      hat: "none5",
      body: "chest",
      hairColor: "pink",
      clothingColor: "green",
      circleColor: "blue",
      lipColor: "pink",
      hatColor: "red",
      faceMaskColor: "white",
      mask: true,
      faceMask: false,
      lashes: false,
    },
    id: 689932,
  },
  {
    data: {
      skinTone: "red",
      eyes: "heart",
      eyebrows: "angry",
      mouth: "grin",
      hair: "afro",
      facialHair: "mediumBeard",
      clothing: "naked",
      accessory: "tinyGlasses",
      graphic: "none",
      hat: "turban",
      body: "breasts",
      hairColor: "black",
      clothingColor: "green",
      circleColor: "blue",
      lipColor: "turqoise",
      hatColor: "black",
      faceMaskColor: "black",
      mask: true,
      faceMask: false,
      lashes: true,
    },
    id: 861133,
  },
  {
    data: {
      skinTone: "brown",
      eyes: "happy",
      eyebrows: "raised",
      mouth: "serious",
      hair: "balding",
      facialHair: "mediumBeard",
      clothing: "dressShirt",
      accessory: "none",
      graphic: "gatsby",
      hat: "turban",
      body: "breasts",
      hairColor: "blonde",
      clothingColor: "green",
      circleColor: "blue",
      lipColor: "pink",
      hatColor: "black",
      faceMaskColor: "red",
      mask: true,
      faceMask: false,
      lashes: true,
    },
    id: 202027,
  },
  {
    data: {
      skinTone: "red",
      eyes: "content",
      eyebrows: "angry",
      mouth: "grin",
      hair: "balding",
      facialHair: "stubble",
      clothing: "vneck",
      accessory: "shades",
      graphic: "none",
      hat: "none4",
      body: "breasts",
      hairColor: "orange",
      clothingColor: "black",
      circleColor: "blue",
      lipColor: "green",
      hatColor: "white",
      faceMaskColor: "red",
      mask: true,
      faceMask: false,
      lashes: true,
    },
    id: 22105,
  },
  {
    data: {
      skinTone: "yellow",
      eyes: "happy",
      eyebrows: "serious",
      mouth: "lips",
      hair: "buzz",
      facialHair: "stubble",
      clothing: "naked",
      accessory: "roundGlasses",
      graphic: "gatsby",
      hat: "turban",
      body: "chest",
      hairColor: "black",
      clothingColor: "black",
      circleColor: "blue",
      lipColor: "pink",
      hatColor: "green",
      faceMaskColor: "green",
      mask: true,
      faceMask: false,
      lashes: true,
    },

    id: 156197,
  },
  {
    data: {
      skinTone: "brown",
      eyes: "squint",
      eyebrows: "angry",
      mouth: "serious",
      hair: "afro",
      facialHair: "none2",
      clothing: "dress",
      accessory: "none",
      graphic: "none",
      hat: "none5",
      body: "chest",
      hairColor: "blue",
      clothingColor: "white",
      circleColor: "blue",
      lipColor: "turqoise",
      hatColor: "black",
      faceMaskColor: "blue",
      mask: true,
      faceMask: false,
      lashes: false,
    },
    id: 111889,
  },
  {
    data: {
      skinTone: "light",
      eyes: "happy",
      eyebrows: "angry",
      mouth: "tongue",
      hair: "long",
      facialHair: "stubble",
      clothing: "vneck",
      accessory: "tinyGlasses",
      graphic: "react",
      hat: "turban",
      body: "chest",
      hairColor: "black",
      clothingColor: "red",
      circleColor: "blue",
      lipColor: "green",
      hatColor: "white",
      faceMaskColor: "black",
      mask: true,
      faceMask: false,
      lashes: false,
    },
    id: 590214,
  },
  {
    data: {
      skinTone: "red",
      eyes: "normal",
      eyebrows: "leftLowered",
      mouth: "sad",
      hair: "none",
      facialHair: "mediumBeard",
      clothing: "vneck",
      accessory: "roundGlasses",
      graphic: "none",
      hat: "none3",
      body: "chest",
      hairColor: "pink",
      clothingColor: "green",
      circleColor: "blue",
      lipColor: "purple",
      hatColor: "white",
      faceMaskColor: "red",
      mask: true,
      faceMask: false,
      lashes: false,
    },
    id: 650599,
  },
  {
    data: {
      skinTone: "red",
      eyes: "dizzy",
      eyebrows: "concerned",
      mouth: "lips",
      hair: "bun",
      facialHair: "mediumBeard",
      clothing: "shirt",
      accessory: "tinyGlasses",
      graphic: "redwood",
      hat: "none3",
      body: "chest",
      hairColor: "blonde",
      clothingColor: "green",
      circleColor: "blue",
      lipColor: "green",
      hatColor: "red",
      faceMaskColor: "white",
      mask: true,
      faceMask: false,
      lashes: false,
    },
    id: 161834,
  },
  {
    data: {
      skinTone: "brown",
      eyes: "squint",
      eyebrows: "angry",
      mouth: "lips",
      hair: "buzz",
      facialHair: "none3",
      clothing: "shirt",
      accessory: "none",
      graphic: "graphQL",
      hat: "none3",
      body: "chest",
      hairColor: "brown",
      clothingColor: "black",
      circleColor: "blue",
      lipColor: "pink",
      hatColor: "black",
      faceMaskColor: "red",
      mask: true,
      faceMask: false,
      lashes: true,
    },
    id: 17379,
  },
  {
    data: {
      skinTone: "dark",
      eyes: "happy",
      eyebrows: "raised",
      mouth: "open",
      hair: "bun",
      facialHair: "none",
      clothing: "naked",
      accessory: "tinyGlasses",
      graphic: "vue",
      hat: "none3",
      body: "chest",
      hairColor: "orange",
      clothingColor: "white",
      circleColor: "blue",
      lipColor: "green",
      hatColor: "green",
      faceMaskColor: "white",
      mask: true,
      faceMask: false,
      lashes: false,
    },
    id: 622598,
  },
  {
    data: {
      skinTone: "light",
      eyes: "dizzy",
      eyebrows: "concerned",
      mouth: "lips",
      hair: "pixie",
      facialHair: "stubble",
      clothing: "naked",
      accessory: "none",
      graphic: "react",
      hat: "none5",
      body: "chest",
      hairColor: "pink",
      clothingColor: "green",
      circleColor: "blue",
      lipColor: "pink",
      hatColor: "blue",
      faceMaskColor: "black",
      mask: true,
      faceMask: false,
      lashes: false,
    },
    id: 486789,
  },
  {
    data: {
      skinTone: "yellow",
      eyes: "simple",
      eyebrows: "serious",
      mouth: "tongue",
      hair: "long",
      facialHair: "mediumBeard",
      clothing: "vneck",
      accessory: "shades",
      graphic: "vue",
      hat: "turban",
      body: "chest",
      hairColor: "orange",
      clothingColor: "white",
      circleColor: "blue",
      lipColor: "pink",
      hatColor: "blue",
      faceMaskColor: "red",
      mask: true,
      faceMask: false,
      lashes: false,
    },
    id: 555268,
  },
  {
    data: {
      skinTone: "red",
      eyes: "leftTwitch",
      eyebrows: "angry",
      mouth: "tongue",
      hair: "bun",
      facialHair: "none2",
      clothing: "naked",
      accessory: "roundGlasses",
      graphic: "none",
      hat: "none5",
      body: "breasts",
      hairColor: "white",
      clothingColor: "black",
      circleColor: "blue",
      lipColor: "purple",
      hatColor: "red",
      faceMaskColor: "white",
      mask: true,
      faceMask: false,
      lashes: true,
    },
    id: 12603,
  },
  {
    data: {
      skinTone: "dark",
      eyes: "normal",
      eyebrows: "leftLowered",
      mouth: "openSmile",
      hair: "bob",
      facialHair: "stubble",
      clothing: "dress",
      accessory: "shades",
      graphic: "vue",
      hat: "none2",
      body: "chest",
      hairColor: "blonde",
      clothingColor: "green",
      circleColor: "blue",
      lipColor: "green",
      hatColor: "white",
      faceMaskColor: "red",
      mask: true,
      faceMask: false,
      lashes: true,
    },
    id: 493363,
  },
  {
    data: {
      skinTone: "dark",
      eyes: "wink",
      eyebrows: "angry",
      mouth: "tongue",
      hair: "balding",
      facialHair: "none3",
      clothing: "dress",
      accessory: "none",
      graphic: "graphQL",
      hat: "none5",
      body: "breasts",
      hairColor: "brown",
      clothingColor: "blue",
      circleColor: "blue",
      lipColor: "pink",
      hatColor: "black",
      faceMaskColor: "white",
      mask: true,
      faceMask: false,
      lashes: false,
    },
    id: 187465,
  },
  {
    data: {
      skinTone: "brown",
      eyes: "heart",
      eyebrows: "raised",
      mouth: "sad",
      hair: "buzz",
      facialHair: "none2",
      clothing: "tankTop",
      accessory: "none",
      graphic: "redwood",
      hat: "none2",
      body: "chest",
      hairColor: "blue",
      clothingColor: "green",
      circleColor: "blue",
      lipColor: "purple",
      hatColor: "blue",
      faceMaskColor: "red",
      mask: true,
      faceMask: false,
      lashes: true,
    },
    id: 332620,
  },
];
