export type DefaultConfig = {
  polkadexFeature?: string;
  polkadexChain: string[];
  gaTrackerKey: string;
  landingPageMarket: string;
  incrementalOrderBook: boolean;
  orderBookSideLimit: number;
  defaultStorageLimit: number;
  defaultTradingViewInterval: number;
  sessionCheckInterval: number;
  balancesFetchInterval: number;
  minutesUntilAutoLogout: number;
  alertDisplayTime: number;
  msPricesUpdates: number;
  maintenanceMode: boolean;
  enableLmp: boolean;
  isBridgeEnabled: boolean;
  availableRoutes: string[];
  underMaintenance: string[];
  mainUrl: string;
  blockedAssets: string[];
  subscanApi: string;
  disabledTheaChains: string[];
  subqueryUrl: string;
  googleApiKey: string;
  googleClientId: string;
  disabledFeatures: Array<Features>;
  defaultTheaSourceChain: string;
  defaultTheaDestinationChain: string;
  contentfulSpaceId: string;
  contentfulAccessToken: string;
  contentfulPreviewToken: string;
  contentfulEnvironment: string;
  contentfulManagementToken: string;
};

export type Features = (typeof features)[number];
export const features = ["googleDriveStore", "payWithAnotherFee"] as const;
