export const USER_TRADE_ACCOUNTS_DATA = "USER_TRADE_ACCOUNT/DATA";
export const USER_TRADE_ACCOUNTS_FETCH = "USER_TRADE_ACCOUNT/FETCH";
export const USER_TRADE_ACCOUNTS_ERROR = "USER_TRADE_ACCOUNT/ERROR";

export const USER_REGISTER_TRADE_ACCOUNT_FETCH = "USER_REGISTER_TRADE_ACCOUNT/FETCH";
export const USER_REGISTER_TRADE_ACCOUNT_DATA = "USER_REGISTER_TRADE_ACCOUNT/DATA";
export const USER_REGISTER_TRADE_ACCOUNT_ERROR = "USER_REGISTER_TRADE_ACCOUNT/ERROR";
export const USER_REGISTER_TRADE_ACCOUNT_RESET = "USER_REGISTER_TRADE_ACCOUNT/RESET";

export const REMOVE_TRADE_ACCOUNT_FROM_BROWSER =
  "USER_TRADE_ACCOUNT/REMOVE_TRADE_ACCOUNT_FROM_BROWSER";
export const USER_TRADE_ACCOUNT_REMOVE_FROM_CHAIN_FETCH =
  "USER_TRADE_ACCOUNT/REMOVE_FROM_CHAIN";
export const USER_TRADE_ACCOUNT_REMOVE_FROM_CHAIN_DATA =
  "USER_TRADE_ACCOUNT/REMOVE_FROM_CHAIN_DATA";
export const USER_TRADE_ACCOUNT_REMOVE_FROM_CHAIN_ERROR =
  "USER_TRADE_ACCOUNT/REMOVE_FROM_CHAIN_ERROR";

export const USER_TRADE_ACCOUNT_UNLOCK = "USER_TRADE_ACCOUNT/UNLOCK_ACCOUNT";

export const USER_TRADE_ACCOUNT_IMPORT_FETCH = "USER_TRADE_ACCOUNT/IMPORT_FETCH";
export const USER_TRADE_ACCOUNT_IMPORT_DATA = "USER_TRADE_ACCOUNT/IMPORT_DATA";
export const USER_TRADE_ACCOUNT_IMPORT_ERROR = "USER_TRADE_ACCOUNT/IMPORT_ERROR";

export const USER_TRADE_ACCOUNT_EXPORT_FETCH = "USER_TRADE_ACCOUNT/EXPORT_FETCH";
export const USER_TRADE_ACCOUNT_EXPORT_DATA = "USER_TRADE_ACCOUNT/EXPORT_DATA";
export const USER_TRADE_ACCOUNT_EXPORT_ACTIVE = "USER_TRADE_ACCOUNT/EXPORT_ACTIVE";

export const USER_TRADE_ACCOUNT_PUSH = "USER_TRADE_ACCOUNT/PUSH";

export const USER_TRADE_ACCOUNT_MODAL_ACTIVE = "USER_TRADE_ACCOUNT_MODAL_ACTIVE/MODAL_ACTIVE";
export const USER_TRADE_ACCOUNT_MODAL_CANCEL = "USER_TRADE_ACCOUNT_MODAL_CANCEL/MODAL_CANCEL";

export const USER_PREVIEW_ACCOUNT_MODAL_ACTIVE =
  "USER_PREVIEW_ACCOUNT_MODAL_ACTIVE/MODAL_ACTIVE";
export const USER_PREVIEW_ACCOUNT_MODAL_CANCEL =
  "USER_PREVIEW_ACCOUNT_MODAL_CANCEL/MODAL_CANCEL";
