export type IColors =
  | "primary"
  | "secondary"
  | "primaryBackground"
  | "primaryBackgroundOpacity"
  | "secondaryBackground"
  | "secondaryBackgroundOpacity"
  | "secondaryBackgroundSolid"
  | "popupBackground"
  | "gradientBackground"
  | "text"
  | "gradient"
  | "green"
  | "orange"
  | "transparent"
  | "none"
  | "black"
  | "white";

export type IIcons =
  | "ArrowTop"
  | "Appearance"
  | "SupportCenter"
  | "Logout"
  | "Support"
  | "Verified"
  | "Avatar"
  | "Attention"
  | "CreditCard"
  | "Bank"
  | "Polkaido"
  | "Polkapool"
  | "Play"
  | "Marketplace"
  | "Document"
  | "Guide"
  | "Lock"
  | "Loan"
  | "Gift"
  | "Airplane"
  | "ArrowBottom"
  | "ArrowVerticalBottom"
  | "Language"
  | "ArrowVerticalTop"
  | "Calendar"
  | "Buy"
  | "Candles"
  | "Clock"
  | "Copy"
  | "Close"
  | "Dashboard"
  | "Edit"
  | "PolkadotJs"
  | "Email"
  | "Chart"
  | "EN"
  | "Exchange"
  | "Expand"
  | "Graph"
  | "Dots"
  | "Help"
  | "History"
  | "Moon"
  | "Swap"
  | "Export"
  | "Expand"
  | "IDO"
  | "OrdersSell"
  | "OrdersBuy"
  | "OrdersAll"
  | "ExchangeBuy"
  | "ExchangeSell"
  | "DoubleExchange"
  | "Deposit"
  | "Withdraw"
  | "News"
  | "Clean"
  | "Notifications"
  | "ArrowRight"
  | "External"
  | "ArrowLeft"
  | "Options"
  | "Order"
  | "OrderAsc"
  | "OrderDes"
  | "Return"
  | "Search"
  | "Sell"
  | "Settings"
  | "Star"
  | "Sun"
  | "Transactions"
  | "Wallet"
  | "En"
  | "Es"
  | "Fr"
  | "Pt"
  | "De";

export type ISizes =
  | "xxxsmall"
  | "xxsmall"
  | "xsmall"
  | "small"
  | "normal"
  | "medium"
  | "large"
  | "xlarge";

export type ITokens =
  | "INCH"
  | "AAVE"
  | "BAL"
  | "COMP"
  | "DOT"
  | "ETH"
  | "LINK"
  | "PDEX"
  | "UNI"
  | "USDT"
  | "BTC"
  | "USD"
  | "EUR"
  | "ZAR"
  | "DASH"
  | string;

export type ITokensName =
  | "Polkadex"
  | "Polkadot"
  | "Ethereum"
  | "Aave"
  | "Compound"
  | "Tether"
  | "Uniswap"
  | "Link"
  | "Basic Token Atention"
  | "1Inch"
  | "Bitcoin"
  | "Dash";

export type Placement =
  | "bottom"
  | "bottom left"
  | "bottom right"
  | "bottom start"
  | "bottom end"
  | "top"
  | "top left"
  | "top right"
  | "top start"
  | "top end"
  | "left"
  | "left top"
  | "left bottom"
  | "start"
  | "start top"
  | "start bottom"
  | "right"
  | "right top"
  | "right bottom"
  | "end"
  | "end top"
  | "end bottom";

export type Nullable<T> = T | null;
export type Optional<T> = T | undefined;