export const POLKADOT_EXTENSION_WALLET_DATA = "EXTENSION_WALLET/DATA";
export const POLKADOT_EXTENSION_WALLET_ERROR = "EXTENSION_WALLET/PERROR";
export const POLKADOT_EXTENSION_WALLET_FETCH = "EXTENSION_WALLET/FETCH";

export const REGISTER_MAIN_ACCOUNT_FETCH = "REGISTER_MAIN_ACCOUNT/FETCH";
export const REGISTER_MAIN_ACCOUNT_DATA = "REGISTER_MAIN_ACCOUNT/DATA";
export const REGISTER_MAIN_ACCOUNT_ERROR = "REGISTER_MAIN_ACCOUNT/ERROR";

export const MAIN_ACCOUNT_SET_FETCH = "EXTENSION_WALLET/MAIN_ACCOUNT_SET_FETCH";
export const MAIN_ACCOUNT_SET_DATA = "EXTENSION_WALLET/MAIN_ACCOUNT_SET_DATA";
export const MAIN_ACCOUNT_SET_ERROR = "EXTENSION_WALLET/MAIN_ACCOUNT_SET_ERROR";

export const EXTENSION_WALLET_RESET = "EXTENSION_WALLET/RESET";
