export const POLKADOT_EXTENSION_WALLET_DATA = "EXTENSION_WALLET/DATA";
export const POLKADOT_EXTENSION_WALLET_ERROR = "EXTENSION_WALLET/PERROR";
export const POLKADOT_EXTENSION_WALLET_FETCH = "EXTENSION_WALLET/FETCH";

export const REGISTER_MAIN_ACCOUNT_FETCH = "REGISTER_MAIN_ACCOUNT/FETCH";
export const REGISTER_MAIN_ACCOUNT_DATA = "REGISTER_MAIN_ACCOUNT/DATA";
export const REGISTER_MAIN_ACCOUNT_ERROR = "REGISTER_MAIN_ACCOUNT/ERROR";

export const REGISTER_MAIN_ACCOUNT_UPDATE_FETCH = "REGISTER_MAIN_ACCOUNT/UPDATE_FETCH";
export const REGISTER_MAIN_ACCOUNT_UPDATE_DATA = "REGISTER_MAIN_ACCOUNT/UPDATE_DATA";
export const REGISTER_MAIN_ACCOUNT_UPDATE_ERROR = "REGISTER_MAIN_ACCOUNT/UPDATE_ERROR";

export const EXTENSION_WALLET_RESET = "EXTENSION_WALLET/RESET";
