export const EXTENSION_WALLET_DATA = "EXTENSION_WALLET/DATA";
export const EXTENSION_WALLET_ERROR = "EXTENSION_WALLET/PERROR";
export const EXTENSION_WALLET_FETCH = "EXTENSION_WALLET/FETCH";

export const MAIN_ACCOUNT_SET_FETCH = "EXTENSION_WALLET/MAIN_ACCOUNT_SET_FETCH";
export const MAIN_ACCOUNT_SET_DATA = "EXTENSION_WALLET/MAIN_ACCOUNT_SET_DATA";
export const MAIN_ACCOUNT_SET_ERROR = "EXTENSION_WALLET/MAIN_ACCOUNT_SET_ERROR";

export const EXTENSION_WALLET_RESET = "EXTENSION_WALLET/RESET";
