export const PROFILE_USER_AUTH_FETCH = "profile/USER_AUTH_FETCH";
export const PROFILE_USER_AUTH_DATA = "profile/USER_AUTH_DATA";
export const PROFILE_USER_AUTH_ERROR = "profile/USER_AUTH_ERROR";

export const PROFILE_USER_FETCH = "profile/GET_USER_FETCH";
export const PROFILE_USER_DATA = "profile/GET_USER_DATA";
export const PROFILE_USER_ERROR = "profile/GET_USER_ERROR";

export const PROFILE_USER_ACTIVITY = "profile/GET_USER_ACTIVITY";
export const PROFILE_RESET_USER = "profile/RESET_USER";

export const PROFILE_USER_CHANGE_INIT_BANNER = "profile/PROFILE_USER_CHANGE_INIT_BANNER";
export const PROFILE_USER_SELECT_ACCOUNT_FETCH = "profile/PROFILE_USER_SELECT_ACCOUNT";
export const PROFILE_USER_SELECT_ACCOUNT_DATA = "profile/PROFILE_USER_SELECT_ACCOUNT_DATA";

export const PROFILE_USER_ACCOUNT_PUSH = "profile/USER_ACCOUNT_PUSH";
export const PROFILE_USER_MAIN_ACCOUNT_PUSH = "profile/PROFILE_USER_MAIN_ACCOUNT_PUSH";
export const PROFILE_USER_TRADE_ACCOUNT_DELETE = "profile/PROFILE_USER_TRADE_ACCOUNT_DELETE";

export const PROFILE_SET_DEFAULT_TRADE_ACCOUNT = "profile/PROFILE_SET_DEFAULT_TRADE_ACCOUNT";

export const PROFILE_SET_PROFILE_AVATAR = "profile/PROFILE_SET_PROFILE_AVATAR";

export const PROFILE_USER_FAVORITE_MARKET_PUSH = "profile/PROFILE_USER_FAVORITE_MARKET_DATA";

export const USER_EVENTSCHANNEL_FETCH = "USER_EVENTS/CHANNEL_FETCH";
export const USER_EVENTSCHANNEL_DATA = "USER_EVENTS/CHANNEL_DATA";
export const USER_EVENTSCHANNEL_ERROR = "USER_EVENTS/CHANNEL_ERROR";
export const USER_UNKNOWN_EVENT = "USER_EVENTS/UNKNOWN_EVENT";
