export const CHANGE_COLOR_THEME = "colorTheme/CHANGE_COLOR_THEME";
export const TOGGLE_CHART_REBUILD = "colorTheme/TOGGLE_CHART_REBUILD";
export const TOGGLE_ORDERS_PAIRS_SWITCHER = "trading/TOGGLE_ORDERS_PAIRS_SWITCHER";
export const TOGGLE_MARKET_SELECTOR = "colorTheme/TOGGLE_MARKET_SELECTOR";
