export const NATIVEAPI_CONNECT_FETCH = "nativeapi/CONNECT_FETCH";
export const NATIVEAPI_CONNECT_DATA = "nativeapi/CONNECT_DATA";
export const NATIVEAPI_CONNECT_ERROR = "nativeapi/CONNECT_ERROR";
export const NATIVEAPI_DISCONNECT_FETCH = "nativeapi/DISCONNECT_FETCH";
export const NATIVEAPI_DISCONNECT_DATA = "nativeapi/DISCONNECT_DATA";
export const RECONNECT_TIME_MS = 30000;
