export const EXTENSION_WALLET_DATA = "EXTENSION_WALLET/DATA";
export const EXTENSION_WALLET_ERROR = "EXTENSION_WALLET/PERROR";
export const EXTENSION_WALLET_FETCH = "EXTENSION_WALLET/FETCH";

export const EXTENSION_WALLET_SET = "EXTENSION_WALLET/SET";
export const EXTENSION_WALLET_RESET = "EXTENSION_WALLET/RESET";
