export type DefaultConfig = {
  polkadexFeature: string;
  polkadexChain: string;
  gaTrackerKey: string;
  landingPageMarket: string;
  withCredentials: boolean;
  incrementalOrderBook: boolean;
  orderBookSideLimit: number;
  defaultStorageLimit: number;
  defaultTradingViewInterval: number;
  sessionCheckInterval: number;
  balancesFetchInterval: number;
  minutesUntilAutoLogout: number;
  alertDisplayTime: number;
  msPricesUpdates: number;
  maintenanceMode: boolean;
  signUpDisabled: boolean;
  reconnectRangerTime: number;
  showShutdownPopup: boolean;
  availableRoutes: string[];
  underMaintenance: string[];
  mainUrl: string;
  blockedAssets: string;
};
