export const USER_TRADE_ACCOUNTS_DATA = "USER_TRADE_ACCOUNT/DATA";
export const USER_TRADE_ACCOUNTS_FETCH = "USER_TRADE_ACCOUNT/FETCH";
export const USER_TRADE_ACCOUNTS_ERROR = "USER_TRADE_ACCOUNT/ERROR";

export const USER_REGISTER_TRADE_ACCOUNT_FETCH = "USER_REGISTER_TRADE_ACCOUNT/FETCH";
export const USER_REGISTER_TRADE_ACCOUNT_DATA = "USER_REGISTER_TRADE_ACCOUNT/DATA";
export const USER_REGISTER_TRADE_ACCOUNT_ERROR = "USER_REGISTER_TRADE_ACCOUNT/ERROR";

export const SET_CURRENT_TRADE_ACCOUNT = "USER_TRADE_ACCOUNT/SET_CURRENT_TRADE_ACCOUNT";
export const SET_CURRENT_TRADE_ACCOUNT_DATA =
  "USER_TRADE_ACCOUNT/SET_CURRENT_TRADE_ACCOUNT_DATA";
export const REMOVE_TRADE_ACCOUNT_FROM_BROWSER =
  "USER_TRADE_ACCOUNT/REMOVE_TRADE_ACCOUNT_FROM_BROWSER";

export const RESET_CURRENT_TRADE_ACCOUNT = "USER_TRADE_ACCOUNT/RESET_CURRENT_TRADE_ACCOUNT";
