projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-central-1
        frontend: javascript
        framework: react
        maxDepth: 2
        amplify: null
        version: 3
extensions:
  amplify:
    version: 3
