export const MARKETS_SET_CURRENT_MARKET = "markets/SET_CURRENT_MARKET";
export const MARKETS_SET_CURRENT_MARKET_IFUNSET =
  "markets/SET_CURRENT_MARKET_IFUNSET";

export const MARKETS_SET_CURRENT_TICKER = "markets/MARKETS_SET_CURRENT_TICKER";
export const MARKET_TICKER_CHANNEL_FETCH = "markets/TICKERS_CHANNEL_FETCH";
export const MARKET_TICKER_CHANNEL_DATA = "markets/TICKER_CHANNEL_DATA";
