// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAnnoucementsFields {
  /** Title */
  title: string;

  /** Cards */
  cards?: IAnnouncementComponent[] | undefined;
}

export interface IAnnoucements extends Entry<IAnnoucementsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "annoucements";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IAnnouncementComponentFields {
  /** Title */
  title: string;

  /** Description */
  description: Document;
}

export interface IAnnouncementComponent
  extends Entry<IAnnouncementComponentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "announcementComponent";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "annoucements" | "announcementComponent";

export type IEntry = IAnnoucements | IAnnouncementComponent;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
