export const SET_SELECT_WALLET = "Wallets/SET_SELECT_WALLET";
export const SET_SELECT_ACCOUNT = "Wallets/SET_SELECT_ACCOUNT";
export const SET_LOCAL_TRADING_ACCOUNT = "Wallets/SET_LOCAL_TRADING_ACCOUNT";
export const SET_SELECT_EXTENSION = "Wallets/SET_SELECT_EXTENSION";
export const SET_TEMP_MNEMONIC = "Wallets/SET_TEMP_MNEMONIC";
export const SET_TEMP_TRADING = "Wallets/SET_TEMP_TRADING";

export const RESET_TEMP_TRADING = "Wallets/RESET_TEMP_TRADING";
export const RESET_TEMP_MNEMONIC = "Wallets/RESET_TEMP_MNEMONIC";
export const RESET_SELECT_WALLET = "Wallets/RESET_SELECT_WALLET";
export const RESET_SELECT_EXTENSION = "Wallets/RESET_SELECT_EXTENSION";
export const LOGOUT = "Wallets/LOGOUT";

export const REMOVE_LOCAL_TRADING_ACCOUNT =
  "Wallets/REMOVE_LOCAL_TRADING_ACCOUNT";
