export const AUTH_SIGN_IN_FETCH = "auth/SIGN_IN_FETCH";
export const AUTH_SIGN_IN_DATA = "auth/SIGN_IN_DATA";
export const AUTH_SIGN_IN_ERROR = "auth/SIGN_IN_ERROR";

export const AUTH_KEYRING_GENERATE_FETCH = "auth/AUTH_KEYRING_GENERATE_FETCH";
export const AUTH_KEYRING_GENERATE_DATA = "auth/AUTH_KEYRING_GENERATE_DATA";
export const AUTH_KEYRING_SIGN_IN_FETCH = "auth/AUTH_KEYRING_SIGN_IN_FETCH";
export const AUTH_KEYRING_SIGN_UP_FETCH = "auth/AUTH_KEYRING_SIGN_UP_FETCH";
export const AUTH_KEYRING_SIGN_IN_DATA = "auth/AUTH_KEYRING_SIGN_IN_DATA";

export const AUTH_SIGN_UP_DATA = "auth/SIGN_UP_DATA";
export const AUTH_SIGN_UP_FETCH = "auth/SIGN_UP_FETCH";
export const AUTH_SIGN_UP_ERROR = "auth/SIGN_UP_ERROR";

export const AUTH_LOGOUT_FETCH = "auth/LOGOUT_FETCH";
export const AUTH_LOGOUT_FAILURE = "auth/LOGOUT_FAILURE";

export const AUTH_CONNECT_PHONE_FETCH = "auth/AUTH_CONNECT_PHONE_FETCH";
export const AUTH_CONNECT_PHONE_DATA = "auth/AUTH_CONNECT_PHONE_DATA";
export const AUTH_CONNECT_PHONE_ERROR = "auth/AUTH_CONNECT_PHONE_ERROR";
