/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://hyl7f5nz7bbcxdhgidh75mau34.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AWS_LAMBDA",
    "Auth": {
        "identityPoolId": "eu-central-1:cce22d71-c414-478d-8dc5-c8121062107b",
        "region": "eu-central-1",
        "identityPoolRegion": "eu-central-1",
        "userPoolId": "eu-central-1_Rllv5siDU",
        "userPoolWebClientId": "3or4hd42mkvfaf0kh7eksphnt9"
    }
};


export default awsmobile;
