/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://b652nqgwcvh4fnd57bfyeosq5e.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": 'API_KEY',
    "aws_appsync_apiKey": "da2-6uhp2pcvxffb7nhb4pqrqhvgji",
    "Auth": {
        "identityPoolId": "ap-south-1:cd2e3e33-8e37-46c0-9d5d-7628020f6c4c",
        "region": "ap-south-1",
        "identityPoolRegion": "ap-south-1",
        "userPoolId": "ap-south-1_PjjzlJrWS",
        "userPoolWebClientId": "7g7opgi0q66qg3jrplq6bb62eh"
    }
};


export default awsmobile;
