/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://tnsmtjx5wnflvih7uusgvkvkte.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AWS_LAMBDA",
    "Auth": {
        "identityPoolId": "ap-south-1:e635faf2-1300-45ad-b594-9f22d9d7193a",
        "region": "ap-south-1",
        "identityPoolRegion": "ap-south-1",
        "userPoolId": "ap-south-1_5niZAl9wZ",
        "userPoolWebClientId": "3jqfmq052q36mt2cgg1t4gprb8"
    }
};


export default awsmobile;
