export const NOTIFICATION_DELETE_ALL = "notification/NOTIFICATION_DELETE_ALL";
export const NOTIFICATION_DATA = "notification/NOTIFICATION_DATA";
export const NOTIFICATION_PUSH = "notification/NOTIFICATION_PUSH";
export const NOTIFICATION_DELETE_BY_ID = "notification/NOTIFICATION_DELETE_BY_ID";
