export const USER_EVENTSCHANNEL_FETCH = "USER_EVENTS/CHANNEL_FETCH";
export const USER_EVENTSCHANNEL_DATA = "USER_EVENTS/CHANNEL_DATA";
export const USER_EVENTSCHANNEL_ERROR = "USER_EVENTS/CHANNEL_ERROR";
export const USER_UNKNOWN_EVENT = "USER_EVENTS/UNKNOWN_EVENT";
